services:
  app:
    build:
      context: .
    container_name: dictmonitoring_app
    restart: unless-stopped
    volumes:
      - .:/var/www
    depends_on:
      - db
    expose:
      - "9000"
    networks:
      dict_custom_net:
        ipv4_address: 192.168.100.10

  web:
    image: nginx:alpine
    container_name: nginx_web
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      dict_custom_net:
        ipv4_address: 192.168.100.11

  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_dict_monitoring
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      dict_custom_net:
        ipv4_address: 192.168.100.12

networks:
  dict_custom_net:
    external: true

volumes:
  mysql_data:
